stages:
  - mirroring
  - test

mirror:
  stage: mirroring
  image: alpine:latest
  before_script:
    - apk update && apk upgrade
    - apk add bash git openssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git clone --mirror git@github.com:tobiasfrust/mirroring-example.git
    - cd mirroring-example
    - git push --mirror git@gitlab.hzdr.de:examples/project-mirroring.git
  only:
    - schedules

test-1:
  stage: test
  image: alpine:latest
  script:
    - echo "Run Tests"
    - exit 0
