stages:
  - mirroring
  - test

mirror:
  stage: mirroring
  image: debian:latest
  before_script:
    - apt-get update -qy
    - apt-get install -qy git-core openssh-client
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - git clone --mirror git@github.com:tobiasfrust/mirroring-example.git
    - cd mirroring-example.git
    - git push --mirror git@gitlab.hzdr.de:examples/project-mirroring.git
#  only:
#    - schedules

test-1:
  stage: test
  image: alpine:latest
  script:
    - echo "Run Tests"
    - exit 0
#  only:
#    - schedules
